CC = g++
SOURCES = abcsort.cpp
EXECUTABLE = abcsort
#OBJECTS=$(SOURCES:.cpp=.o)

all: build run
build:  
	@$(CC) $(SOURCES) -o $(EXECUTABLE)
	@echo Program building done.
run:
	@echo Running program:
	@$(EXECUTABLE)
